apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- $relname := .Release.Name -}}
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | repeat 5 | quote }}
  food: {{ .food | upper | quote }}
  toppping: |-
    {{- range $.Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }} 
  toppings2: |-
    {{- range $index, $topping := $.Values.pizzaToppings }}
      {{ $index }}: {{ $topping }}
    {{- end }} 
  sizes: |-
    {{- range tuple "small" "medium" "large" }}
    - {{ . }}
    {{- end }} 
  release: {{ $.Release.Name }}
  release2: {{ $relname }}
  {{- end }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: "true"
  {{- end }}
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}